<a href="https://colab.research.google.com/github/Dhruv-958/DS/blob/main/Central_tendency.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("Salary_Data.csv")
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

In [4]:
df.describe()

               Age  Years of Experience         Salary
count  6702.000000          6701.000000    6699.000000
mean     33.620859             8.094687  115326.964771
std       7.614633             6.059003   52786.183911
min      21.000000             0.000000     350.000000
25%      28.000000             3.000000   70000.000000
50%      32.000000             7.000000  115000.000000
75%      38.000000            12.000000  160000.000000
max      62.000000            34.000000  250000.000000

In [5]:
df['Salary'].mean()

115326.96477086132

In [25]:
df1 = df.groupby(['Salary','Age'])

In [26]:
df1.describe()

              Years of Experience
                            count  mean  std   min   25%   50%   75%   max
Salary   Age
350.0    29.0                 1.0   1.5  NaN   1.5   1.5   1.5   1.5   1.5
500.0    31.0                 1.0   4.0  NaN   4.0   4.0   4.0   4.0   4.0
550.0    25.0                 1.0   1.0  NaN   1.0   1.0   1.0   1.0   1.0
579.0    23.0                 1.0   1.0  NaN   1.0   1.0   1.0   1.0   1.0
25000.0  21.0                18.0   0.0  0.0   0.0   0.0   0.0   0.0   0.0
...                           ...   ...  ...   ...   ...   ...   ...   ...
228000.0 49.0                 1.0  23.0  NaN  23.0  23.0  23.0  23.0  23.0
240000.0 51.0                 8.0  24.0  0.0  24.0  24.0  24.0  24.0  24.0
250000.0 45.0                 1.0  21.0  NaN  21.0  21.0  21.0  21.0  21.0
         50.0                 1.0  25.0  NaN  25.0  25.0  25.0  25.0  25.0
         52.0                 1.0  24.0  NaN  24.0  24.0  24.0  24.0  24.0

[938 rows x 8 columns]

In [27]:
df.isna().sum()

Age                    2
Gender                 2
Education Level        3
Job Title              2
Years of Experience    3
Salary                 5
dtype: int64

In [28]:
df1 = df.dropna()
df1.isna().sum()

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

In [29]:
df1

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

In [30]:
def age_group(age) :
  if age <= 39:
    return "Young Adult"
  elif age <=59:
    return "Middle Age"
  else:
    return "Old Adult"

df1["Age"] = df1["Age"].apply(age_group)
df1

<ipython-input-30-e8a4730f3a62>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["Age"] = df1["Age"].apply(age_group)

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,Young Adult,Male,Bachelor's,Software Engineer,5.0,90000.0
1,Young Adult,Female,Master's,Data Analyst,3.0,65000.0
2,Middle Age,Male,PhD,Senior Manager,15.0,150000.0
3,Young Adult,Female,Bachelor's,Sales Associate,7.0,60000.0
4,Middle Age,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,Middle Age,Female,PhD,Director of Marketing,20.0,200000.0
6700,Young Adult,Male,High School,Sales Associate,3.0,50000.0
6701,Young Adult,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,Middle Age,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,Young Adult,Female,High School,Sales Executive,1.0,35000.0

In [31]:
df1["Age"].value_counts()

Age
Young Adult    5258
Middle Age     1428
Old Adult        12
Name: count, dtype: int64

In [33]:
df1.groupby(["Age"])["Salary"].mean()

Age
Middle Age     171445.844538
Old Adult      194221.833333
Young Adult     99908.712248
Name: Salary, dtype: float64

In [36]:
df1.groupby(["Age"])["Salary"].agg(pd.Series.mode)

Age
Middle Age     190000.0
Old Adult      200000.0
Young Adult     55000.0
Name: Salary, dtype: float64

In [37]:
df1.groupby(["Age"])["Salary"].median()

Age
Middle Age     180000.0
Old Adult      200000.0
Young Adult     95000.0
Name: Salary, dtype: float64

In [40]:
min = df1.groupby(["Age"])["Salary"].min()
min

Age
Middle Age      60000.0
Old Adult      179180.0
Young Adult       350.0
Name: Salary, dtype: float64

In [41]:
max = df1.groupby(["Age"])["Salary"].max()
max

Age
Middle Age     250000.0
Old Adult      200000.0
Young Adult    210000.0
Name: Salary, dtype: float64

In [42]:
range = max - min
range

Age
Middle Age     190000.0
Old Adult       20820.0
Young Adult    209650.0
Name: Salary, dtype: float64

In [44]:
std_dev = df1.groupby(["Age"])["Salary"].std()
std_dev

Age
Middle Age     27346.224381
Old Adult       8251.159046
Young Adult    47323.624121
Name: Salary, dtype: float64

In [46]:
var = np.square(std_dev)
var

Age
Middle Age     7.478160e+08
Old Adult      6.808163e+07
Young Adult    2.239525e+09
Name: Salary, dtype: float64